# -*- coding: utf-8 -*-
"""TiRex Classification Model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BpafJRB03C6JizjEHSZU5h1xD_TUgC49

#  Install TiRex package
"""

!pip install 'tirex-ts[notebooks,gluonts,hfdataset,classification]' -q
!pip install aeon

!pip install 'git+https://github.com/NX-AI/tirex.git#egg=tirex-ts[classification]'

"""# Load Example Data"""

import torch
from aeon.datasets import load_italy_power_demand
from sklearn.preprocessing import LabelEncoder

# Load train data
train_X, train_y = load_italy_power_demand(split="train")

# Load test data
test_X, test_y = load_italy_power_demand(split="test")

# Encode string labels -> integers
label_encoder = LabelEncoder()
train_y = label_encoder.fit_transform(train_y)
test_y = label_encoder.transform(test_y)

# Convert to torch tensors
train_X = torch.tensor(train_X, dtype=torch.float32)
test_X = torch.tensor(test_X, dtype=torch.float32)

train_y = torch.tensor(train_y, dtype=torch.long)
test_y = torch.tensor(test_y, dtype=torch.long)

print(train_X.shape, train_y.shape)
print(test_X.shape, test_y.shape)

train_X[:5]

train_y[:5]

"""# Initialize Embedding model and Classification Head

## 1. Random Forest Classifier
"""

from tirex.models.classification import TirexRFClassifier

classifier = TirexRFClassifier(n_estimators=50, max_depth=10, random_state=42, batch_size=256)

"""### Fit Model"""

fit_meta = classifier.fit((train_X, train_y))

"""### Prediction results"""

from sklearn.metrics import accuracy_score, f1_score

pred_y = classifier.predict(test_X)
pred_y = pred_y.cpu().numpy()

print("Accuracy " + str(accuracy_score(test_y, pred_y)))
print("F1 Score " + str(f1_score(test_y, pred_y, average="macro")))

"""## 2. Linear Regression Classifier"""

from tirex.models.classification import TirexLinearClassifier

classifier_2 = TirexLinearClassifier(data_augmentation=False, compile=False)

fit_meta_2 = classifier_2.fit((train_X, train_y))

from sklearn.metrics import accuracy_score, f1_score

pred_y = classifier_2.predict(test_X)
pred_y = pred_y.cpu().numpy()

print("Accuracy " + str(accuracy_score(test_y, pred_y)))
print("F1 Score " + str(f1_score(test_y, pred_y, average="macro")))

"""## 3. Gradient Boosting Classifier"""

from tirex.models.classification import TirexGBMClassifier

classifier_3 = TirexGBMClassifier(data_augmentation=False, compile=False)

fit_meta_3 = classifier_3.fit((train_X, train_y))

from sklearn.metrics import accuracy_score, f1_score

pred_y = classifier_3.predict(test_X)
pred_y = pred_y.cpu().numpy()

print("Accuracy " + str(accuracy_score(test_y, pred_y)))
print("F1 Score " + str(f1_score(test_y, pred_y, average="macro")))